### PR TITLE
build: add 'clean' and 'server' npm scripts

### LINKED ISSUE #3: Use `hexo` in `node_modules/` instead of global one
For example

``` json
"scripts": {
  "serve": "hexo server",
  "build": "hexo build"
}
```

Then we can reuse `./node_modules/.bin/hexo` and the user do not have to install `hexo-cli` globally (for existing Hexo site).

[How to Solve the Global npm Module Dependency Problem](http://www.sitepoint.com/solve-global-npm-module-dependency-problem/)

---

**Update (2019-07-11)**

`npx` is included in `npm` since v5.3, it will use binaries in `./node_modules/.bin`, and install command temporarily if not available in `node_modules/`.
[How to use npx: the npm package runner](https://blog.scottlogic.com/2018/04/05/npx-the-npm-package-runner.html)

Here are my latest commands:

```sh
# local serve
npx hexo clean && npx hexo server

# deploy
npx hexo clean && npx hexo generate && npx hexo deploy
```

### PR DESCRIPTION
**Pull request by curbengh**
Continuation of #21 
Closes #3

### CODE REVIEW

**Comment by tomap** [comment]
I get why we need the build script (=> for zeit commands, and maybe other similar services)
But I don't get why the npx hexo server would not work? why the need to add it to the scripts?

**Comment by curbengh** [comment]
`clean` is a common npm script, so user who familiar with npm ecosystem will feel right at home.

Frankly, I never thought of the necessity of this PR. Now I think about it, perhaps it can serve as a hexo (very) basic usage guide. If that's the case, we might as well add `deploy` script. But it's not a good guide either, whereas `hexo --help` at least explain something.

I'm actually just following @YoshinoriN suggestion 😅 . I'm fine with having them or not.

**Comment by SukkaW** [comment]
I think adding those npm scripts are fine. After all, only users who are familiar with npm will use them.

**Comment by tomap** [comment]
ok, I'm fine with your explanation

**Comment by curbengh** [comment]
Added `deploy`.

**Pull request merged**
